name: Main CI # action 명
on: # 이벤트 트리거
  merge: # push event에 반응
    branches: # github repository의 branch가
      - deploy # master 일 경우만

jobs: # jobs
  build:
    runs-on: ubuntu-latest
    # using Ubuntu 18.04 LTS
    steps: # steps
      - name: Git clone
        uses: actions/checkout@v2

      - name: Npm install #
        run: npm install # npm install

      - name: Build #
        run: npm run build # code build

      - name: Deploy # 배포
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          SOURCE_DIR: "dist"
