name: Main CI # action 명
on: # 이벤트 트리거
  push: # push event에 반응
    branches: # github repository의 branch가
      - front-patch-2 # master 일 경우만

jobs: # jobs
  build: 
    runs-on: ubuntu-latest
    # using Ubuntu 18.04 LTS
    steps: # steps
      - uses: actions/checkout@front-patch-2
      
      - name: Cache node modules      # node modules 캐싱
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-build-
            ${{ runner.OS }}-

      - name: Npm install # 
         run: npm install # npm install
      
      - name: Build #
         run: npm run build # code build
         
      - name: Deploy # 배포
         env:
          AWS_ACCESS_KEY_ID: '${{ secrets.AWS_ACCESS_KEY_ID }}' 
          AWS_SECRET_ACCESS_KEY: '${{ secrets.AWS_SECRET_ACCESS_KEY }}' 
         run: |
            aws s3 cp \ 
                --recursive \
                --region ap-northeast-2 \
                dist s3://Naver-Reservation
